apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.78ac0a1
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.c27bcfa
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.6.2-rc38
