apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.5.0
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.6.0-rc.3be6702
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.7.8-rc1
