apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.5.0-rc.0580f4c
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.5.0-rc.222c327
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.7.7-rc2
