apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.12.0
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.15.0-rc.aa56b22
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.7.10-rc34
