apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.c83c8e3
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.c916118
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.6.2-rc41
