apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.2.0-rc.edc4221
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.2.0-rc.4014688
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.7.4-rc2
