apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.c0edf2d
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.54cc4e0
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.6.2-rc47
