apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.19.0-rc.ce373f3
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.22.0-rc.aa5882d
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.8.5-rc23
