apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.89c1f8f
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.e0d9dab
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.6.2-rc32
