apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.20.0-rc.6192514
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.26.0-rc.986a7e7
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.9.1-rc12
