apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.19.0
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.25.0
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.9.0-rc8
