apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.11.0-rc.265cac7
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.13.0
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.7.10-rc25
