apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.13.0-rc.7a86a5c
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.16.0-rc.b222db8
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.7.10-rc42
