apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.16.0
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.18.0
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.8.3
