global:
  kubefirst-pro-apiVersion: v2.9.1-rc2
  kubefirst-pro-uiVersion: v2.9.1-rc4
  kubefirstVersion: v2.9.1-rc1
kubefirst-pro-api:
  nameOverride: pro-api
kubefirst-pro-ui:
  nameOverride: pro-ui
