apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.14.0-rc.c36f4f5
description: Colony helm chart
name: colony
type: application
version: 0.2.2-rc145
