apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.14.0-rc.4e7d5fd
description: Colony helm chart
name: colony
type: application
version: 0.2.2-rc122
