apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.11.0-rc.2f4c3a2
description: Colony helm chart
name: colony
type: application
version: 0.1.1-rc34
