apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.11.0-rc.9a38415
description: Colony helm chart
name: colony
type: application
version: 0.1.1-rc35
