apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.12.0-rc.0bd1444
description: Colony helm chart
name: colony
type: application
version: 0.2.1-rc1
