apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.9.0-rc.1550a07
description: Colony helm chart
name: colony
type: application
version: 0.1.0-rc0
