apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.13.0-rc.5f461cb
description: Colony helm chart
name: colony
type: application
version: 0.2.2-rc59
