apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.69.0-rc.f95b616
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.132.0-rc.2b5e438
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.8.5-rc6
