apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.65.0-rc.345ba10
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.124.0-rc.66091e7
- name: kubefirst-api-ee
  repository: https://charts.konstruct.io
  version: 1.9.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.8.0-rc1
