apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.73.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.136.0-rc.5b2f162
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.10.4-rc1
