apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.71.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.134.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.9.1
