apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.72.0-rc.7e5abd4
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.134.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.9.2-rc2
