apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.73.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.137.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.10.5
