apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.66.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.127.0-rc.1109abd
- name: kubefirst-api-ee
  repository: https://charts.konstruct.io
  version: 1.9.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.8.2-rc1
