apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.64.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.123.0-rc.834f728
- name: kubefirst-api-ee
  repository: https://charts.konstruct.io
  version: 1.9.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.7.10-rc7
