apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.68.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.131.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.8.4-rc6
