apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.61.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.111.0-rc.eb59e17
- name: kubefirst-api-ee
  repository: https://charts.konstruct.io
  version: 1.9.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.7.0-rc1
