apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.67.0-rc.22574f5
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.131.0-rc.4264bdb
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.8.4-rc2
