apiVersion: v2
dependencies:
- name: console
  repository: https://charts.konstruct.io
  version: 2.64.0
- name: kubefirst-api
  repository: https://charts.konstruct.io
  version: 0.121.0-rc.86e1c48
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.7.10-rc1
