console:
  domain: kubefirst.dev
global:
  consoleVersion: v2.6.2-rc19
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.6.2-rc18
  kubefirstVersion: v2.6.1
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
