console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.8.1-rc4
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.8.2-rc2
  kubefirstVersion: v2.8.1
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
