console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.9.0-rc4
  kubefirst-api-eeVersion: v2.9.0-rc2
  kubefirst-apiVersion: v2.9.0-rc6
  kubefirstVersion: v2.9.0
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
