console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.10.0-rc1
  kubefirst-api-eeVersion: v2.10.0-rc0
  kubefirst-apiVersion: v2.10.0-rc2
  kubefirstVersion: v2.10.0-rc0
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
