global:
  consoleVersion: v2.7.5-rc6
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.7.7-rc2
  kubefirstVersion: v2.7.7
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets

kubefirst-api:
  nameOverride: "api"

console:
  nameOverride: "console"
  domain: kubefirst.dev
