console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.9.2-rc2
  kubefirst-api-eeVersion: v2.9.1-rc1
  kubefirst-apiVersion: v2.9.2-rc5
  kubefirstVersion: v2.9.1
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
