console:
  domain: kubefirst.dev
global:
  consoleVersion: v2.6.2-rc22
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.7.1-rc1
  kubefirstVersion: v2.7.0
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
