console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.8.5-rc1
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.8.5-rc3
  kubefirstVersion: v2.8.4
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
