console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.7.9-rc4
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.7.10-rc5
  kubefirstVersion: v2.7.9
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
