console:
  domain: kubefirst.dev
global:
  consoleVersion: v2.7.8-rc1
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.7.8-rc2
  kubefirstVersion: v2.7.7
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
