console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.10.2-rc1
  kubefirst-api-eeVersion: v2.10.0-rc0
  kubefirst-apiVersion: v2.10.4-rc2
  kubefirstVersion: v2.10.3
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
