console:
  domain: kubefirst.dev
  nameOverride: console
global:
  consoleVersion: v2.8.0-rc4
  kubefirst-api-eeVersion: v2.6.1-rc2
  kubefirst-apiVersion: v2.8.0-rc5
  kubefirstVersion: 2.8.0-rc0
kubefirst-api:
  nameOverride: api
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
